#!/bin/bash

# BetMonkey Casino Setup Script
# Configura automáticamente todo el entorno necesario para el casino de ruleta

set -e  # Exit on error

echo "🎰 BetMonkey Casino - Setup Script"
echo "===================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Function to print colored messages
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Step 1: Check dependencies
echo "Step 1: Checking dependencies..."
echo "--------------------------------"

if ! command_exists node; then
    print_error "Node.js is not installed. Please install Node.js first."
    exit 1
fi
print_success "Node.js $(node --version) found"

if ! command_exists npm; then
    print_error "npm is not installed. Please install npm first."
    exit 1
fi
print_success "npm $(npm --version) found"

if ! command_exists solana; then
    print_error "Solana CLI is not installed. Please install from https://docs.solana.com/cli/install-solana-cli-tools"
    exit 1
fi
print_success "Solana CLI $(solana --version | head -n1) found"

echo ""

# Step 2: Install dependencies
echo "Step 2: Installing npm dependencies..."
echo "---------------------------------------"
if [ ! -d "node_modules" ]; then
    npm install
    print_success "Dependencies installed"
else
    print_info "Dependencies already installed (skipping)"
fi
echo ""

# Step 3: Create necessary directories
echo "Step 3: Creating directories..."
echo "--------------------------------"
mkdir -p data
mkdir -p logs
mkdir -p keys
print_success "Created: data/, logs/, keys/"
echo ""

# Step 4: Generate facilitator keypair
echo "Step 4: Generating facilitator keypair..."
echo "------------------------------------------"
FACILITATOR_KEYPAIR="./keys/facilitator-keypair.json"

if [ -f "$FACILITATOR_KEYPAIR" ]; then
    print_info "Facilitator keypair already exists at $FACILITATOR_KEYPAIR"
    if [ -t 0 ]; then
        read -p "Do you want to generate a new one? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            solana-keygen new --outfile "$FACILITATOR_KEYPAIR" --force --no-bip39-passphrase
            print_success "New facilitator keypair generated"
        fi
    else
        print_info "Non-interactive mode: keeping existing keypair"
    fi
else
    solana-keygen new --outfile "$FACILITATOR_KEYPAIR" --no-bip39-passphrase
    print_success "Facilitator keypair generated at $FACILITATOR_KEYPAIR"
fi

# Extract keys
FACILITATOR_PUBKEY=$(solana-keygen pubkey "$FACILITATOR_KEYPAIR")
print_info "Facilitator public key: $FACILITATOR_PUBKEY"

# Convert keypair to base58 private key
# Using Node.js to convert the keypair JSON to base58
FACILITATOR_PRIVATE_KEY=$(node -e "
const fs = require('fs');
const bs58 = require('bs58');
const keypair = JSON.parse(fs.readFileSync('$FACILITATOR_KEYPAIR', 'utf8'));
const secretKey = Uint8Array.from(keypair);
console.log(bs58.default.encode(secretKey));
")

echo ""

# Step 5: Generate merchant keypair (or use same as facilitator for testing)
echo "Step 5: Setting up merchant wallet..."
echo "--------------------------------------"
print_info "Using facilitator as merchant for testing (same wallet)"
MERCHANT_ADDRESS="$FACILITATOR_PUBKEY"
print_info "Merchant address: $MERCHANT_ADDRESS"
echo ""

# Step 6: Create .env file
echo "Step 6: Creating .env file..."
echo "------------------------------"

if [ -f ".env" ]; then
    print_info ".env file already exists"
    if [ -t 0 ]; then
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Keeping existing .env file"
        else
            rm .env
            CREATE_ENV=true
        fi
    else
        print_info "Non-interactive mode: keeping existing .env file"
    fi
else
    CREATE_ENV=true
fi

if [ "$CREATE_ENV" = true ]; then
    cat > .env << EOF
# BetMonkey Casino Environment Configuration
# Auto-generated by setup-casino.sh

# Facilitator Configuration
FACILITATOR_PORT=3001
FACILITATOR_PRIVATE_KEY=$FACILITATOR_PRIVATE_KEY
FACILITATOR_PUBLIC_KEY=$FACILITATOR_PUBKEY

# Server Configuration
SERVER_PORT=3000
SERVER_URL=http://localhost:3000
FACILITATOR_URL=http://localhost:3001

# Casino Configuration
CASINO_PORT=3003
CASINO_URL=http://localhost:3003

# Merchant Configuration
MERCHANT_SOLANA_ADDRESS=$MERCHANT_ADDRESS

# Solana Configuration
SOLANA_RPC_URL=https://api.devnet.solana.com
SOLANA_WS_URL=wss://api.devnet.solana.com
SOLANA_NETWORK=devnet

# Database Configuration
# NOTE: Using single unified database for both casino and nonces (x402 protocol)
DATABASE_PATH=./data/casino.db
CASINO_DATABASE_PATH=./data/casino.db

# Payment Configuration
MAX_PAYMENT_AMOUNT=1000000000
NONCE_EXPIRY_HOURS=24

# Testing Configuration (set to false for real blockchain transactions)
SIMULATE_TRANSACTIONS=false

# Optional: USDC Token Configuration (Devnet)
USDC_MINT_ADDRESS=4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU
USDC_DECIMALS=6

# HTTP Request Configuration
REQUEST_TIMEOUT=30000
RETRY_ATTEMPTS=3
RETRY_DELAY=1000
REQUEST_BODY_LIMIT=10mb

# Background Task Configuration
CLEANUP_INTERVAL_HOURS=1

# Roulette Payment Amounts (in lamports)
# Quick play (red/black/odd/even): 0.001 SOL = 1,000,000 lamports
ROULETTE_QUICK_AMOUNT=1000000
# Custom play (complex bets): 0.01 SOL = 10,000,000 lamports
ROULETTE_CUSTOM_AMOUNT=10000000
EOF
    print_success ".env file created with configuration"
fi
echo ""

# Step 7: Fund facilitator wallet
echo "Step 7: Funding facilitator wallet on devnet..."
echo "------------------------------------------------"
print_info "Requesting airdrop of 2 SOL to facilitator..."

# Set Solana to use devnet
solana config set --url devnet > /dev/null

# Check current balance
CURRENT_BALANCE=$(solana balance "$FACILITATOR_PUBKEY" 2>/dev/null | awk '{print $1}')
print_info "Current balance: $CURRENT_BALANCE SOL"

if (( $(echo "$CURRENT_BALANCE < 0.5" | bc -l) )); then
    print_info "Balance is low, requesting airdrop..."
    if solana airdrop 2 "$FACILITATOR_PUBKEY" --url devnet; then
        print_success "Airdrop successful!"
        NEW_BALANCE=$(solana balance "$FACILITATOR_PUBKEY" 2>/dev/null | awk '{print $1}')
        print_info "New balance: $NEW_BALANCE SOL"
    else
        print_error "Airdrop failed. You may need to request manually or wait a bit."
        print_info "Try: solana airdrop 2 $FACILITATOR_PUBKEY --url devnet"
    fi
else
    print_success "Balance is sufficient ($CURRENT_BALANCE SOL)"
fi
echo ""

# Step 8: Build the project
echo "Step 8: Building the project..."
echo "--------------------------------"
npm run build
print_success "Project built successfully"
echo ""

# Step 9: Summary
echo "=========================================="
echo "✅ Setup Complete!"
echo "=========================================="
echo ""
echo "Configuration Summary:"
echo "----------------------"
echo "Facilitator Public Key: $FACILITATOR_PUBKEY"
echo "Merchant Address: $MERCHANT_ADDRESS"
echo "Network: Solana Devnet"
echo ""
echo "Services:"
echo "---------"
echo "• Facilitator: http://localhost:3001"
echo "• Generic Server: http://localhost:3000"
echo "• Casino Server: http://localhost:3003"
echo ""
echo "Next Steps:"
echo "-----------"
echo "1. Start all services: npm start"
echo "   (or individually: npm run dev:facilitator, npm run dev:casino)"
echo ""
echo "2. Run the roulette game: ./play-roulette.sh"
echo ""
echo "3. Monitor logs: npm run logs"
echo ""
echo "Important Files:"
echo "----------------"
echo "• Facilitator keypair: $FACILITATOR_KEYPAIR"
echo "• Environment config: .env"
echo "• Database (unified): ./data/casino.db"
echo "  ├─ Casino data (users, wallets, games, bets)"
echo "  └─ Nonces (x402 protocol, replay protection)"
echo ""

# Step 10: Setup player
echo "Step 10: Setting up player..."
echo "------------------------------"
if [ -f "./setup-player.sh" ]; then
    bash ./setup-player.sh
else
    print_info "Player setup script not found, skipping..."
fi

print_success "Ready to play! 🎰"
echo ""
